apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
        - name: analysis
          image: monitor-analysis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: analysis
spec:
  selector:
    app: analysis
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30083
      protocol: TCP
  type: NodePort
