apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor-client
  template:
    metadata:
      labels:
        app: monitor-client
    spec:
      containers:
        - name: client
          image: monitor-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ETCD_HOST
              value: "etcd-service"
            - name: ETCD_PORT
              value: "2379"
            - name: GRPC_ADDR
              value: "monitor-server:50051"
