apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-config
data:
  config.json: |
    {
      "interval": 5,
      "metrics": ["cpu", "memory", "diskio", "network"],
      "plugins": [
        "module.plugins._cpu.CPUPlugin",
        "module.plugins._ram.RAMPlugin",
        "module.plugins._diskio.DiskIOPlugin",
        "module.plugins._network.NetworkPlugin",
        "module.plugins._process_count.ProcessCountPlugin"
      ],
      "master_hostname": "LAPTOP-UMVK4LFU"
    }
