services:

  kafka:
    container_name: broker
    image: apache/kafka:3.9.1
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller 
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0 
      - KAFKA_LOG_FLUSH_INTERVAL_MESSAGES=1
    ports:
      - "9092:9092"
      - "9094:9094"
  
  # Kafka Visualization:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'broker'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092'
    ports:
      - "9095:8080"
    depends_on:
      - kafka
  etcd:
    image: quay.io/coreos/etcd:v3.6.0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=etcd
    ports:
      - "12379:2379"
      - "12380:2380"